### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by noraj** [dolevf/graphw00f#24]
Could you release a `pyproject.toml` file to make install a&nd packaging easier?

- [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/)
- [How to Publish an Open-Source Python Package to PyPI](https://realpython.com/pypi-publish-python-package/)
- [The pyproject.toml file](https://python-poetry.org/docs/pyproject/)

**Comment by noraj** [comment]
I see one as been PRed in #17 for the issue #18

**Comment by noraj** [comment]
This also solve the dependency listing we don't have currently and face dependency issue

```
Traceback (most recent call last):
  File "/usr/share/graphw00f/./main.py", line 21, in <module>
    from graphw00f.lib import (
  File "/usr/share/graphw00f/graphw00f/lib.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

and have to open all python files to seek the right dependencies to install.
